name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      matrix:
        required: true
        type: string     
jobs:
  job1:
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: self-hosted
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.include.project }}"
          echo "${{ matrix.include.config }}"     

  # pr-terraform:
  #   needs: [get-matrix]
  #   strategy:
  #     matrix: ${{ fromJson(needs.get-matrix.outputs.matrix) }}
  #     fail-fast: false
  #   runs-on:
  #     - self-hosted
  #   steps:
  #     - name: Clean up runner
  #       run: |
  #         echo "${{ matrix.environment }}"
  #         echo "${{ matrix.location }}"
