name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      matrix:
        required: true
        type: string     
jobs:
  get-matrix:
    runs-on:
      - self-hosted  
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}      
    steps:
      - id: get-matrix
        name: output matrix
        run: |
          echo "::set-output name=matrix::${{ inputs.matrix }}"
  test-get:
    runs-on:
      - self-hosted
    steps:
      - name: test-get
        run: |
          echo "${{needs.get-matrix.outputs.matrix}}"         

  # pr-terraform:
  #   needs: [get-matrix]
  #   strategy:
  #     matrix: ${{ fromJson(needs.get-matrix.outputs.matrix) }}
  #     fail-fast: false
  #   runs-on:
  #     - self-hosted
  #   steps:
  #     - name: Clean up runner
  #       run: |
  #         echo "${{ matrix.environment }}"
  #         echo "${{ matrix.location }}"
